### ISSUE TITLE
"Creating Project" Button stucks

### ISSUE THREAD

**Issue by scharph** [arno01/taiga#6]
When i want to create a project, the "Create Project" - Button stucks!

![screenshot from 2017-05-10 18-14-57](https://cloud.githubusercontent.com/assets/15950114/25909384/4cab82aa-35ad-11e7-9f9b-f1ea986496c1.png)

Is there a log where i can look for this?

**Comment by arno01** [comment]
@scharph there is a chance that Taiga is trying to send an email, but since it can't, it might cause that "loop" button.

Could you please try commenting all fields related to the email in `seeds/local.py.tmpl` file?
 E.g. line 47 to line 55. https://github.com/arno01/taiga/blob/master/seeds/local.py.tmpl#L47

And try re-creating the taiga.

Please let me know.

**Comment by scharph** [comment]
yes it works now!

i commented all of this:
```
#DEFAULT_FROM_EMAIL = "${NOREPLY_EMAIL}"
#SERVER_EMAIL = DEFAULT_FROM_EMAIL

#EMAIL_BACKEND = "${EMAIL_BACKEND}"
#EMAIL_USE_TLS = ${EMAIL_USE_TLS}
#EMAIL_HOST = "${EMAIL_HOST}"
#EMAIL_HOST_USER = "${EMAIL_HOST_USER}"
#EMAIL_HOST_PASSWORD = "${EMAIL_HOST_PASSWORD}"
#EMAIL_PORT = ${EMAIL_HOST_PORT}
```

Thank you @arno01 for your reply!

Maybe you can help me with the a issue (#7) too?
